import streamlit as st
st.set_page_config(page_title="Hall of Fame", page_icon="🏆")

st.markdown("# Hall of Fame")
st.markdown("### #6: The Regifting Challenge ([repo link](https://github.com/uncultivate/dollar-auction/))")
st.markdown("#### 🥇 ???")
st.markdown("#### 🥈 ???")
st.markdown("#### 🥉 ???")
st.divider()
st.markdown("### #5: The Regifting Challenge ([repo link](https://github.com/uncultivate/regifting/))")
st.markdown("#### 🥇 Avaricious Rapacity")
st.markdown("#### 🥈 The Grinch")
st.markdown("#### 🥉 revelrous ryan")
st.divider()
st.markdown("### #4: The Beast from 3 East ([repo link](https://github.com/uncultivate/monster-hunt/))")
st.markdown("#### 🥇 Leprechaun")
st.markdown("#### 🥈 rapid ryan")
st.markdown("#### 🥉 Saboteur")
st.divider()
st.markdown("### #3: The UpLift Challenge ([repo link](https://github.com/uncultivate/elevator-master/))")
st.markdown("#### 🥇 Michellevator")
st.markdown("#### 🥈 ASR")
st.markdown("#### 🥉 efficient elevator ryan")
st.divider()
st.markdown("### #2: Tulip Coin")
st.markdown("#### 🥇 ASR")
st.markdown("#### 🥈 Volatile")
st.markdown("#### 🥉 tulip tycoon ryan")
st.divider()
st.markdown("### #1: The Prisoner's Dilemma Game")
st.markdown("#### 🥇 grudge holder")
st.markdown("#### 🥈 wenng")
st.markdown("#### 🥉 the punisher")
